export const ActionTypes = {
  ADD_NOTIFY: "ADD_NOTIFY",
  GET_NOTIFY: "GET_NOTIFY",
  DEL_NOTIFY: "DEL_NOTIFY",
  ADD_SERVICE_NOTIFY: "ADD_SERVICE_NOTIFY",
  GET_SERVICE_NOTIFY: "GET_SERVICE_NOTIFY",
  DEL_SERVICE_NOTIFY: "DEL_SERVICE_NOTIFY",
};
